version: 0.2

env:
  variables:
    S3_BUCKET_NAME: $S3_BUCKET_NAME
    CLOUDFRONT_DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID
  exported-variables:
    - S3_BUCKET_NAME
    - CLOUDFRONT_DISTRIBUTION_ID

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    on-failure: ABORT
    commands:
      - echo "Building project..."
      - npm run build:components
      - npx tailwindcss -i ./assets/css/style.css -o ./public/css/style.css --minify
      - npm run compress:js

  post_build:
    on-failure: ABORT
    commands:
      - echo "Build complete. Files ready for deployment."

      - echo "Emptying bucket $S3_BUCKET_NAME"
      - aws s3 rm s3://$S3_BUCKET_NAME --recursive

      - echo "Syncing public/ directory to S3 bucket $S3_BUCKET_NAME"
      - aws s3 sync public/ s3://$S3_BUCKET_NAME --exact-timestamps

      # Set metadata on the extension-less files
      - echo "Applying metadata for abstract URLs"
      - ./src/apply-metadata.sh

      # Invalidate cloudfront cache
      - echo "Invalidating CloudFront cache for distribution $CLOUDFRONT_DISTRIBUTION_ID"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
